print("Installing Quarry...")
shell.run("wget https://raw.githubusercontent.com/Vipth/Turtle-Programs/main/Quarry.lua quarry")
print("Installing Refuel...")
shell.run("wget https://raw.githubusercontent.com/Vipth/Turtle-Programs/main/Refuel.lua refuel")
print("Installing Update...")
shell.run("wget https://raw.githubusercontent.com/Vipth/Turtle-Programs/main/update%20quarry.lua update")
print("Finished Installing Programs--")
print("Enjoy quarrying!")